# Keep empty since we are using a Harmony v7 output 
# (see issue #34 https://github.com/broadinstitute/pe2loaddata/issues/34)
channels:
channelid:
    1: OrigBrightfield
    2: OrigER
    3: OrigMito
    4: OrigAGP
    5: OrigRNA
    6: OrigDNA
metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    PositionX: PositionX
    PositionY: PositionY
    PositionZ: PositionZ
    AbsPositionZ: AbsPositionZ
